-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.10.0.111.2
-- Module  Version: 7.5
-- Wed Nov 28 16:56:41 2018

-- parameterized module component declaration
component ramdqtest
    port (Clock: in  std_logic; ClockEn: in  std_logic; 
        Reset: in  std_logic; WE: in  std_logic; 
        Address: in  std_logic_vector(11 downto 0); 
        Data: in  std_logic_vector(11 downto 0); 
        Q: out  std_logic_vector(11 downto 0));
end component;

-- parameterized module component instance
__ : ramdqtest
    port map (Clock=>__, ClockEn=>__, Reset=>__, WE=>__, Address(11 downto 0)=>__, 
        Data(11 downto 0)=>__, Q(11 downto 0)=>__);
