#!/bin/sh
set -e

# There is a known firmware issue with wcn3620 causing
# the firmware to sporadically not forward authentication
# packets (submitted through DXE). A workaround consist in
# reseting the interface to reload the firmware.

# we monitor wireless events
command="iw event"

# interface to monitor
iface="wlan0"

# string to trigger the workaround
trigger1="*${iface}*auth*timed*out"

wifi_reset() {
	# is it wcn36xx ?
	wcn36xx=$(grep wcn36xx /sys/class/net/${iface}/device/uevent || true)
	if [ -z ${wcn36xx} ]; then
		echo "${iface} is not wcn36xx"
		return
	fi

	echo "Resetting ${iface}"

	# Announce it in klog
	echo "$0: firmware bug detected, resetting ${iface}" > /dev/kmsg

	# Stop interface
	ifconfig ${iface} down

	# Reset remote proc to reload the wcnss firmware
	# echo stop  > $(dirname /sys/devices/platform/soc/*.wcnss/remoteproc/remoteproc*/state)/state
	# echo start  > $(dirname /sys/devices/platform/soc/*.wcnss/remoteproc/remoteproc*/state)/state

	# Interface should already be up, but just in case...
	# sleep 5
	ifconfig ${iface} up
}

while true; do
	stdbuf -oL ${command} |
	while IFS= read -r line; do
		case "$line" in
			${trigger1}) 	wifi_reset  ;;
			*)
		esac
	done
done
