#!/bin/bash

docker ps -a | grep osp-builder &>/dev/null && docker rm osp-builder &> /dev/null
docker images | grep osp-builder &>/dev/null && docker rmi osp-builder &> /dev/null

OS=$(uname)
docker &> /dev/null
NEED_DOCKER=$?

if [ $NEED_DOCKER -ne 0 ]
then
  if [ $OS = "Darwin" ]
  then
    open https://store.docker.com/editions/community/docker-ce-desktop-mac
    read -p "Install Docker for Mac and then press any key once installed and running." -n1 -s && echo
  else
    echo "Install Docker and then press any key once installed and running."
    read -p "See the README file for link to help on this" -n1 -s && echo
  fi
fi

docker build -t osp-builder .
#docker create -it -v $PWD/opt:/opt --privileged  --name osp-builder -h osp-builder osp-builder

exit 0
