#!/bin/sh

fastboot flash partition gpt_both0.bin
fastboot flash hyp hyp.mbn
fastboot flash rpm rpm.mbn
fastboot flash sbl1 sbl1.mbn
fastboot flash tz tz.mbn
fastboot flash aboot emmc_appsboot.mbn
fastboot flash cdt sbc_1.0_8016.bin
fastboot flash fsg fs_image_linux.tar.gz.mbn.img

fastboot erase boot
fastboot erase rootfs
fastboot erase devinfo
