-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.10.0.111.2
-- Module  Version: 5.7
-- Sat Jun  2 11:04:49 2018

-- parameterized module component declaration
component primary_pll
    port (CLKI: in  std_logic; RST: in  std_logic; CLKOP: out  std_logic);
end component;

-- parameterized module component instance
__ : primary_pll
    port map (CLKI=>__, RST=>__, CLKOP=>__);
