-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.10.0.111.2
-- Module  Version: 5.7
-- Fri Dec 14 12:11:27 2018

-- parameterized module component declaration
component plltest
    port (CLKI: in  std_logic; CLKOP: out  std_logic);
end component;

-- parameterized module component instance
__ : plltest
    port map (CLKI=>__, CLKOP=>__);
