[ActiveSupport PAR]
; Global primary clocks
GLOBAL_PRIMARY_USED = 3;
; Global primary clock #0
GLOBAL_PRIMARY_0_SIGNALNAME = adc_clk_copy_c;
GLOBAL_PRIMARY_0_DRIVERTYPE = SLICE;
GLOBAL_PRIMARY_0_LOADNUM = 12;
; Global primary clock #1
GLOBAL_PRIMARY_1_SIGNALNAME = toggle;
GLOBAL_PRIMARY_1_DRIVERTYPE = SLICE;
GLOBAL_PRIMARY_1_LOADNUM = 12;
; Global primary clock #2
GLOBAL_PRIMARY_2_SIGNALNAME = clock_c;
GLOBAL_PRIMARY_2_DRIVERTYPE = PIO;
GLOBAL_PRIMARY_2_LOADNUM = 11;
; # of global secondary clocks
GLOBAL_SECONDARY_USED = 1;
; Global secondary clock #0
GLOBAL_SECONDARY_0_SIGNALNAME = spi_clk_c;
GLOBAL_SECONDARY_0_DRIVERTYPE = PIO;
GLOBAL_SECONDARY_0_LOADNUM = 6;
GLOBAL_SECONDARY_0_SIGTYPE = CLK;
; I/O Bank 0 Usage
BANK_0_USED = 0;
BANK_0_AVAIL = 51;
BANK_0_VCCIO = 3.3V;
BANK_0_VREF1 = NA;
; I/O Bank 1 Usage
BANK_1_USED = 14;
BANK_1_AVAIL = 52;
BANK_1_VCCIO = 3.3V;
BANK_1_VREF1 = NA;
; I/O Bank 2 Usage
BANK_2_USED = 4;
BANK_2_AVAIL = 52;
BANK_2_VCCIO = 1.8V;
BANK_2_VREF1 = NA;
; I/O Bank 3 Usage
BANK_3_USED = 2;
BANK_3_AVAIL = 16;
BANK_3_VCCIO = 3.3V;
BANK_3_VREF1 = NA;
; I/O Bank 4 Usage
BANK_4_USED = 0;
BANK_4_AVAIL = 16;
BANK_4_VCCIO = 3.3V;
BANK_4_VREF1 = NA;
; I/O Bank 5 Usage
BANK_5_USED = 3;
BANK_5_AVAIL = 20;
BANK_5_VCCIO = 1.8V;
BANK_5_VREF1 = NA;
